version: '3.8'
services:
  mariadb:
    image: 'mariadb:10'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '--silent', '--password=theVeryp@ssw0rd' ]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=theVeryp@ssw0rd
      - MYSQL_DATABASE=pushdeer
  redis:
    image: 'redis:7'
    healthcheck:
      test: [ 'CMD', 'redis-cli','ping' ]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  app:
    build:
      context: .
      dockerfile: './docker/product/Dockerfile'
    volumes:
      - './:/app'
    ports:
      - '5200:5200'
    working_dir: '/app'
    healthcheck:
      test: [ 'CMD', 'php', '/app/bin/laravels', 'info' ]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DISABLE_DEFAULT_SERVER=1
      - LARAVELS_WORKER_NUM=4
      - LARAVELS_TASK_WORKER_NUM=8
      - APN_CERTIFICATE_SECRET=64wtMhU4mULj
      - APN_BUNDLE_ID_APP=com.pushdeer.self.ios
      - APN_BUNDLE_ID_CLIP=com.pushdeer.self.ios.Clip
volumes:
  mariadb_data: